### ISSUE TITLE
!command add uptime {text} makes !uptime do {text} instead of intended behavior 

### ISSUE THREAD

**Issue by mikaelssen** [mikaelssen/JefBot#10]
Might have to look into this, as custom commands still eat the default commands, or we can leave it and use it to meme?

**Comment by DrVirite** [comment]
Custom commands are aliases that get matched after main commands

**Comment by mikaelssen** [comment]
Yes, but it still ate the !uptime command. Not really a critical issue.

**Comment by mikaelssen** [comment]
Commit e1fca666cccdf6488af5809c8ca2b70cf8055e61 Fixed this 👍
